---
- hosts: db
  roles:
#    - { role: 'common' }
#    - { role: 'swaptrasher' }
#    - { role: 'add_user' }
#    - { role: 'ssh_setup' }
    - { role:  'add_users' }
    - { role: 'setup_ssh_for_users' }
    - { role: 'sudoers' }
